name: Deploy

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - run: npm ci
    - run: npm run build
    - run: npm test

    - run: cat stats.json | jq .numbers

    - run: npm install -g netlify-cli@2.54.0
    - run: netlify deploy --prod --dir=public
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

